repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        exclude: completions/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: completions/
        args: [--config=test/setup.cfg]
        additional_dependencies: [flake8-bugbear==20.1.4]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        exclude: completions/
        args: [--settings-path=test/setup.cfg]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        exclude: completions/
        args: [--config-file=test/setup.cfg]
